from celery_app import celery
from mail import send_email
from datetime import datetime, timedelta
import csv
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


@celery.task
def send_daily_reminders():
    from main import app
    from models import Student, PlacementDrive

    with app.app_context():
        drives = PlacementDrive.query.filter_by(status='Approved').all()
        upcoming = [
            d for d in drives
            if d.deadline >= datetime.utcnow()
            and d.deadline <= datetime.utcnow() + timedelta(days=3)
        ]

        if not upcoming:
            return

        students = Student.query.all()

        for student in students:
            if not student.user.active or student.user.status == 'Blocked':
                continue

            applied_drive_ids = {a.drive_id for a in student.applications}

            eligible_upcoming = []
            for drive in upcoming:
                eligible_depts = [d.strip() for d in drive.eligible_departments.split(',')] if drive.eligible_departments else []
                eligible_years = [int(y.strip()) for y in drive.eligible_years.split(',')] if drive.eligible_years else []

                is_eligible = (
                    (not eligible_depts or student.department in eligible_depts) and
                    (not eligible_years or student.year_of_study in eligible_years) and
                    (student.cgpa >= drive.min_cgpa) and
                    (drive.drive_id not in applied_drive_ids)
                )

                if is_eligible:
                    eligible_upcoming.append(drive)

            if not eligible_upcoming:
                continue

            drive_lines = '\n'.join(
                f"- {d.drive_name} by {d.company.name} | Deadline: {d.deadline.strftime('%d %b %Y')}"
                for d in eligible_upcoming
            )

            body = f"""Hi {student.name},

This is a reminder that the following placement drives have deadlines within the next 3 days and you haven't applied yet:

{drive_lines}

Login to the Placement Portal to apply before the deadline.

Regards,
Institute Placement Cell
"""
            send_email(
                to_email=student.user.email,
                subject='Reminder: Upcoming Placement Drive Deadlines',
                body=body
            )


@celery.task
def send_monthly_report():
    from main import app
    from models import PlacementDrive, Application, Student, Company, User

    with app.app_context():
        now = datetime.utcnow()
        first_of_month = now.replace(day=1, hour=0, minute=0, second=0, microsecond=0)

        drives_this_month = PlacementDrive.query.filter(
            PlacementDrive.created_on >= first_of_month
        ).all()

        applications_this_month = Application.query.filter(
            Application.applied_at >= first_of_month
        ).all()

        selected_this_month = [a for a in applications_this_month if a.status == 'Selected']

        total_students = Student.query.count()
        total_companies = Company.query.count()

        drive_rows = ''.join(
            f"<tr><td>{d.drive_name}</td><td>{d.company.name}</td><td>{d.status}</td><td>{d.deadline.strftime('%d %b %Y')}</td></tr>"
            for d in drives_this_month
        )

        html_body = f"""
<html>
<body>
<h2>Monthly Placement Activity Report</h2>
<p><strong>Report Month:</strong> {now.strftime('%B %Y')}</p>
<hr/>
<h4>Summary</h4>
<table border="1" cellpadding="6" cellspacing="0">
  <tr><th>Metric</th><th>Count</th></tr>
  <tr><td>Total Students Registered</td><td>{total_students}</td></tr>
  <tr><td>Total Companies Registered</td><td>{total_companies}</td></tr>
  <tr><td>Drives Created This Month</td><td>{len(drives_this_month)}</td></tr>
  <tr><td>Applications This Month</td><td>{len(applications_this_month)}</td></tr>
  <tr><td>Students Selected This Month</td><td>{len(selected_this_month)}</td></tr>
</table>
<br/>
<h4>Drives This Month</h4>
<table border="1" cellpadding="6" cellspacing="0">
  <tr><th>Drive Name</th><th>Company</th><th>Status</th><th>Deadline</th></tr>
  {drive_rows if drive_rows else '<tr><td colspan="4">No drives this month.</td></tr>'}
</table>
<br/>
<p>This report was auto-generated by the Placement Portal Application.</p>
</body>
</html>
"""
        admin = User.query.filter_by(role='Admin').first()
        if admin:
            send_email(
                to_email=admin.email,
                subject=f'Monthly Placement Report - {now.strftime("%B %Y")}',
                body=html_body,
                is_html=True
            )


@celery.task
def export_applications_csv(student_id, student_email):
    from main import app
    from models import Application, Student

    with app.app_context():
        student = Student.query.filter_by(student_id=student_id).first()
        if not student:
            return

        applications = Application.query.filter_by(student_id=student_id).all()

        export_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'static', 'exports')
        os.makedirs(export_dir, exist_ok=True)
        filepath = os.path.join(export_dir, f'applications_student_{student_id}.csv')

        with open(filepath, 'w', newline='') as csvfile:
            writer = csv.writer(csvfile)
            writer.writerow(['Application ID', 'Student ID', 'Company Name', 'Drive Title', 'Application Status', 'Applied At'])
            for application in applications:
                writer.writerow([
                    application.application_id,
                    application.student_id,
                    application.company.name,
                    application.drive.drive_name,
                    application.status,
                    application.applied_at.strftime('%Y-%m-%d %H:%M:%S')
                ])

        send_email(
            to_email=student_email,
            subject='Your Application History Export is Ready',
            body=f"""Hi {student.name},

Your placement application history has been exported successfully.

You can download it from:
http://127.0.0.1:5000/static/exports/applications_student_{student_id}.csv

Regards,
Institute Placement Cell
"""
        )